name: Hassan Ali
meta_description: "Open Source, Blogging about technology"

markdown: kramdown
highlighter: rouge
avatar: https://s.gravatar.com/avatar/dae0df6c0200723ea430c45900e6a7bc?s=200
twitter: https://twitter.com/helfiwalcott
logo: false
paginate: 15
baseurl: /
domain_name: 'https://helfi92.github.io/'
google_analytics: 'UA-81712137-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://helfi92.github.io/'
author:         'Hassan Ali'
